=== ClusterLabs/pacemaker-1.0/crm/crm-1.0.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- 
     This document describes the XML elements used by the CRM. 

     It can be found on the web at: 
	http://wiki.linux-ha.org/ClusterResourceManager/DTD1.0


     For reasons of user availability, the annotations formerly found here
     are now located at:

	http://wiki.linux-ha.org/ClusterResourceManager/DTD1.0/Annotated

     which is also linked to directly by the page above.
 
-->

<!ELEMENT cib (configuration, status)>
<!ATTLIST cib
          cib-last-written CDATA    #IMPLIED

          admin_epoch  CDATA    #REQUIRED
          epoch        CDATA    #REQUIRED
          num_updates  CDATA    #REQUIRED
          num_peers    CDATA    #IMPLIED        

          dc_uuid      CDATA    #IMPLIED
          ccm_transition CDATA  #IMPLIED
          have_quorum    (true|1|false|0)   'false'
          ignore_dtd     (true|1|false|0)   #IMPLIED
          cib_feature_revision  CDATA   #IMPLIED
          crm_feature_set       CDATA   #IMPLIED

          generated    CDATA    #IMPLIED        
          crm-debug-origin CDATA    #IMPLIED>

<!ELEMENT configuration (crm_config, nodes, resources, constraints)>
<!-- Annotated version -->

<!ELEMENT crm_config (cluster_property_set|nvpair)*>
<!ELEMENT cluster_property_set (rule*, attributes)>
<!ATTLIST cluster_property_set
          id                CDATA        #REQUIRED
          score             CDATA        #IMPLIED>

<!ELEMENT nodes       (node*)>
<!-- Annotated version -->

<!ELEMENT node (instance_attributes*)>
<!ATTLIST node
          id            CDATA         #REQUIRED
          uname         CDATA         #REQUIRED
          description   CDATA         #IMPLIED
          type          (normal|member|ping) #REQUIRED>
<!ELEMENT resources   (primitive|group|clone|master_slave)*>
<!-- Annotated version -->

<!ELEMENT primitive (operations?, instance_attributes*)>
<!ATTLIST primitive
          id                CDATA        #REQUIRED
          description       CDATA        #IMPLIED
          class             (ocf|lsb|heartbeat|stonith) #REQUIRED
          type              CDATA        #REQUIRED
          provider          CDATA        #IMPLIED

          is_managed            (true|1|false|0)                     'true'
          on_stopfail           (ignore|stonith|block)           #IMPLIED
          restart_type          (ignore|restart)                 'ignore'
          multiple_active       (stop_start|stop_only|block)     'stop_start'
          resource_stickiness   (0|INFINITY|-INFINITY)           '0'
          start_prereq          (nothing|quorum|fencing)         #IMPLIED>
<!-- Annotated version -->

<!ELEMENT operations (op*)>
<!ELEMENT op (instance_attributes*)>
<!ATTLIST op
          id            CDATA         #REQUIRED
          name          CDATA         #REQUIRED
          description   CDATA         #IMPLIED
          interval      CDATA         #IMPLIED
          timeout       CDATA         #IMPLIED
          disabled	(true|1|false|0)   'false'
          role       (Master|Slave|Started|Stopped) 'Started'
          prereq     (nothing|quorum|fencing)   #IMPLIED
          on_fail    (nothing|block|stop|fence) #IMPLIED>
<!-- Annotated version -->

<!ELEMENT group (primitive+,instance_attributes*)>
<!ATTLIST group
          id                    CDATA               #REQUIRED
          description   CDATA               #IMPLIED

          is_managed            (true|1|false|0)                     'true'
          on_stopfail           (ignore|stonith|block)           #IMPLIED
          restart_type          (ignore|restart)                 'ignore'
          multiple_active       (stop_start|stop_only|block)     'stop_start'
          resource_stickiness   (0|INFINITY|-INFINITY)           '0'
          start_prereq          (nothing|quorum|fencing)         #IMPLIED

          ordered               (true|1|false|0)                     'true'
          collocated            (true|1|false|0)                     'true'>
<!ELEMENT clone (instance_attributes*, (primitive|group))>
<!ATTLIST clone
          id            CDATA               #REQUIRED
          description   CDATA               #IMPLIED

          is_managed            (true|1|false|0)                     'true'
          on_stopfail           (ignore|stonith|block)           #IMPLIED
          restart_type          (ignore|restart)                 'ignore'
          multiple_active       (stop_start|stop_only|block)     'stop_start'
          resource_stickiness   (0|INFINITY|-INFINITY)           '0'
          start_prereq          (nothing|quorum|fencing)         #IMPLIED
          notify                (true|1|false|0)                     'false'

          globally_unique       (true|1|false|0)                     'true'

          ordered       (true|1|false|0)     'true'
          interleave    (true|1|false|0)     'false'>
<!ELEMENT master_slave (instance_attributes*, (primitive|group))>
<!ATTLIST master_slave
          id            CDATA       #REQUIRED
          description   CDATA       #IMPLIED

          is_managed            (true|1|false|0)                     'true'
          on_stopfail           (ignore|stonith|block)           #IMPLIED
          restart_type          (ignore|restart)                 'ignore'
          multiple_active       (stop_start|stop_only|block)     'stop_start'
          resource_stickiness   (0|INFINITY|-INFINITY)           '0'
          start_prereq          (nothing|quorum|fencing)         #IMPLIED
          notify                (true|1|false|0)                     'false'

          globally_unique       (true|1|false|0)                     'true'

          ordered          (true|1|false|0)  'true'
          interleave       (true|1|false|0)  'false'>
<!-- Annotated version -->

<!ELEMENT instance_attributes (rule*, attributes)>
<!ATTLIST instance_attributes
          id                CDATA        #REQUIRED
          score             CDATA        #IMPLIED>

<!-- Annotated version -->

<!ELEMENT constraints (rsc_order*, rsc_colocation*, rsc_location*)>
<!ELEMENT rsc_order (lifetime?)>
<!ATTLIST rsc_order
          id        CDATA #REQUIRED
          from      CDATA #REQUIRED
          action    (start|stop)        'start'
          type      (before|after)      'after'
          to        CDATA #REQUIRED
          symetrical    (true|1|false|0)    'true'>
<!-- Annotated version -->

<!ELEMENT rsc_colocation (lifetime?)>
<!ATTLIST rsc_colocation
          id        CDATA #REQUIRED
          from      CDATA #REQUIRED
          to        CDATA #REQUIRED
          score     (INFINITY|-INFINITY) #REQUIRED>
<!-- Annotated version -->

<!ELEMENT rsc_location (lifetime?,rule+)>
<!ATTLIST rsc_location
          id          CDATA #REQUIRED
          description CDATA #IMPLIED
          rsc         CDATA #REQUIRED>
<!ELEMENT lifetime (rule+)>
<!-- Annotated version -->

<!ELEMENT rule (expression|time_expression|rule)+>
<!ATTLIST rule
          id                    CDATA     #REQUIRED
          role                  CDATA     #IMPLIED
          score                 CDATA     #IMPLIED
          score_attribute       CDATA     #IMPLIED
          boolean_op (or|and)     'and'>
<!-- Annotated version -->

<!ELEMENT expression EMPTY>
<!ATTLIST expression
          id         CDATA                    #REQUIRED
          attribute  CDATA                    #REQUIRED
          operation  (lt|gt|lte|gte|eq|ne|defined|not_defined) #REQUIRED
          value      CDATA                    #IMPLIED
          type       (integer|string|version) 'string'>
<!-- Annotated version -->

<!ELEMENT date_expression (date_spec?,duration?)>
<!ATTLIST date_expression
        operation  (in_range|date_spec|gt|lt) 'in_range'
        start      CDATA  #IMPLIED
        end        CDATA  #IMPLIED>
<!-- Annotated version -->

<!ELEMENT date_spec EMPTY>
<!ATTLIST date_spec
        monthdays  CDATA  #IMPLIED
        weekdays   CDATA  #IMPLIED
        yeardays   CDATA  #IMPLIED
        months     CDATA  #IMPLIED
        weeks      CDATA  #IMPLIED
        weekyears  CDATA  #IMPLIED
        years      CDATA  #IMPLIED
        moon       CDATA  #IMPLIED>

<!ELEMENT duration EMPTY>
<!ATTLIST duration
        monthdays  CDATA  #IMPLIED
        weekdays   CDATA  #IMPLIED
        yeardays   CDATA  #IMPLIED
        months     CDATA  #IMPLIED
        weeks      CDATA  #IMPLIED
        years      CDATA  #IMPLIED>
<!-- Annotated version -->

<!ELEMENT status (node_state*)>
<!ELEMENT node_state (transient_attributes|lrm)*>
<!ATTLIST node_state
        id              CDATA                   #REQUIRED
        uname           CDATA                   #REQUIRED
        ha              (active|dead)           #IMPLIED
        crmd            (online|offline)        'offline'
        join            (pending|member|down)   'down'
        expected        (pending|member|down)   'down'
        in_ccm          (true|1|false|0)        'false'
	crm-debug-origin CDATA                  #IMPLIED
        shutdown        CDATA                   #IMPLIED
        clear_shutdown  CDATA                   #IMPLIED>
<!ELEMENT lrm (lrm_resources)>
<!ATTLIST lrm id CDATA #REQUIRED>

<!-- Annotated version -->

<!ELEMENT lrm_resources (lrm_resource*)>
<!ELEMENT lrm_resource (lrm_rsc_op*)>
<!ATTLIST lrm_resource
          id            CDATA #REQUIRED
          class             (lsb|ocf|heartbeat|stonith) #REQUIRED
          type              CDATA        #REQUIRED
          provider          CDATA        #IMPLIED>

<!ELEMENT lrm_rsc_op EMPTY>
<!ATTLIST lrm_rsc_op
          id            CDATA #REQUIRED
          operation     CDATA #REQUIRED
          op_status     CDATA #REQUIRED
          rc_code               CDATA #REQUIRED
          call_id               CDATA #REQUIRED
          rsc_state             CDATA #IMPLIED
          crm-debug-origin      CDATA #IMPLIED
          transition_key        CDATA #IMPLIED
          op_digest             CDATA #IMPLIED
          interval              CDATA #REQUIRED
          transition_magic      CDATA #REQUIRED>

<!ELEMENT nvpair EMPTY>
<!ATTLIST nvpair
          id            CDATA #REQUIRED
          name          CDATA #REQUIRED
          value         CDATA #IMPLIED>
<!ELEMENT parameters EMPTY>
<!ELEMENT attributes (nvpair*)>
<!ELEMENT transient_attributes (instance_attributes*)>
<!ATTLIST transient_attributes id CDATA #IMPLIED>

<!-- ============================================================== -->
<!-- ============================================================== -->

<!--
 The Transition Graph is an ordered list of synapses, which consist of a
 list of pre-conditions (events) they are waiting for / triggering on
 and a (list of) actions which are initiated when they "fire". The first
 synapse to have a matching input "consumes" the event unless specified
 differently.
 
-->

<!ELEMENT transition_graph (action_set*,errors*)>

<!-- When all inputs to a synapse are satisfied, the synapse fires the
     actions.
     
     "reset" states whether after having fired once, the synapse resets
     and accepts input again. "no": After having fired, the synapse
     becomes completely inactive. "yes": it completely resets. "greedy":
     The synapse will still 'consume' input, but not fire again.
-->

<!ELEMENT synapse (inputs,action_set)>
<!ATTLIST synapse
	  id	CDATA		#REQUIRED
	  reset	(no|yes|greedy) 'greedy'
	  priority CDATA	#IMPLIED>

<!ELEMENT inputs (trigger+)>

<!-- event_spec specifies the event we are looking for.
     This can be anything from "rsc foo started somewhere / on node X",
     "STONITH of node A completed", "DEFAULT" etc... 

     If an event is "consumed", no further inputs in other synapses will
     be triggered by it. If "no", the event will pass through,
     triggering us but otherwise completely unaltered. If "marks", we
     simply remember that the event has been accepted somewhere, but
     pass it on.
     
-->
<!ELEMENT trigger (rsc_state*,node_state*,pseudo_event*,crm_event*)>
<!ATTLIST trigger
	  id		CDATA #REQUIRED
	  consumes	(no|yes|marks) 'marks'>


<!-- STONITH events end up being rsc_ops; remember that we hope to
     simply invoke 'STONITH Resource Agent' and feed it with appropriate
     parameters.

  -->
<!ELEMENT action_set (rsc_op*,pseudo_event*,crm_event*)>

<!-- The resource object inside the rsc_op object differs from the
     resources list only in content, not in syntax.
     - it is pre-processed, ie there's a maximum of one set of
       instance_parameters
     
     on_node is the uname of the node on which to trigger the operation.

     The operation is the command passed to the Resource Agent.

     "allow_fail" when set to true, the transition isnt aborted when the 
     action fails.  eg. a stop or shutdown isnt fatal when a STONITH is also
     pending for that node.

-->

<!ELEMENT rsc_op (primitive, attributes)>
<!ATTLIST rsc_op
	id	      CDATA	#REQUIRED
	operation     CDATA	#REQUIRED
	on_node	      CDATA	#REQUIRED
	on_node_uuid  CDATA	#REQUIRED
	timeout	      CDATA	#REQUIRED
	allow_fail    (true|1|false|0) 'false'>

<!-- For added flexibility, an action can trigger an event, which is
     then consumed somewhere else. Woah. Cool. 
-->
<!ELEMENT pseudo_event (attributes)>
<!ATTLIST pseudo_event
	id	      CDATA	#REQUIRED
	operation     CDATA	#REQUIRED
	on_node	      CDATA	#REQUIRED
	on_node_uuid  CDATA	#REQUIRED
	timeout	      CDATA	#REQUIRED
	allow_fail    (true|1|false|0) 'false'>
	
<!-- crm_event: We can instruct a crmd to shutdown (maybe the whole node?),
     sign-out cleanly, or to retrigger the DC election.
-->
<!ELEMENT crm_event (attributes)>
<!ATTLIST crm_event
	id	      CDATA	#REQUIRED
	allow_fail    (true|1|false|0) 'false'
	on_node	      CDATA	#REQUIRED
	on_node_uuid  CDATA	#REQUIRED
	timeout	      CDATA	#REQUIRED
	operation (shutdown|signout|signup|election) #REQUIRED>

<!-- ============================================================== -->
<!-- ============================================================== -->

<!-- not currently used -->
<!ELEMENT msg_addr EMPTY>
<!ATTLIST msg_addr
	part		(src|dst)	#REQUIRED
	subsystem	(dc|crmd|dcib|cib|pe|te|lrm|admin) #REQUIRED
	host		CDATA		#IMPLIED>

=== ClusterLabs/pacemaker-1.0/pengine/test06/simple1.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<cib num_updates="1" epoch="1" admin_epoch="0" ingore-dtd="none">
  <configuration>
    <crm_config><cluster_property_set id="cib-bootstrap-options"><attributes>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
      <nvpair id="symmetric_cluster" name="symmetric_cluster" value="true"/>
    </attributes></cluster_property_set></crm_config>
    <nodes>
      <node id="node1" uname="node1" type="member"/>
    </nodes>
    <resources>
      <primitive id="rsc1" class="heartbeat" type="apache"/>
    </resources>
    <constraints>
    </constraints>
  </configuration>
  <status>
    <node_state id="node1" ha="active" uname="node1" crmd="offline" join="down" expected="down" in_ccm="true"/>
  </status>
</cib>

=== ClusterLabs/pacemaker-1.0/crm/pengine/testcases/simple10.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<cib>
 <configuration>
  <nodes>
    <node id="node1" uname="node1" type="member"/>
  </nodes>
  <resources>
     <resource id="rsc1" class="heartbeat" type="apache" priority="1.0" version="2.0"/>
  </resources>
  <constraints>
      <rsc_location id="run_rsc1" rsc="rsc1">
	<rule id="can1" result="can"/>
      </rsc_location>
  </constraints>
 </configuration>
 <status>
    <node_state id="node1" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true">
      <lrm>
	<lrm_agents>
	  <lrm_agent class="heartbeat" type="apache" version="1.0"/>
	</lrm_agents>
        <lrm_resources/>
      </lrm>
    </node_state>
 </status>
</cib>

=== ClusterLabs/pacemaker-1.0/crm/pengine/testcases/rec-rsc-0.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<cib>
  <configuration>
    <crm_config><cluster_property_set id="cib-bootstrap-options"><attributes>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
      <nvpair id="symmetric_cluster" name="symmetric_cluster" value="true"/>
    </attributes></cluster_property_set></crm_config>
    <nodes>
      <node id="uuid1" uname="node1" type="member"/>
      <node id="uuid2" uname="node2" type="member"/>
    </nodes>
    <resources>
      <primitive id="rsc1" class="heartbeat" type="apache"/>
    </resources>
    <constraints/>
  </configuration>
  <status>
    <node_state id="uuid1" uname="node1" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true">
      <lrm>
        <lrm_resources>
          <lrm_resource id="rsc1" class="heartbeat" type="apache">
            <lrm_rsc_op id="rsc1_start_0" operation="start" interval="0" rsc_state="start_failed" op_status="4" rc_code="152" call_id="1" op_digest="f2317cad3d54cec5d7d7aa7d0bf35cf8"/>
	  </lrm_resource>
        </lrm_resources>
      </lrm>
    </node_state>
    <node_state id="uuid2" uname="node2" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true">
      <lrm>
        <lrm_resources>
          <lrm_resource id="rsc1" class="heartbeat" type="apache">
            <lrm_rsc_op id="rsc1_start_0" operation="start" interval="0" rsc_state="start_failed" op_status="4" rc_code="152" call_id="1" op_digest="f2317cad3d54cec5d7d7aa7d0bf35cf8"/>
	  </lrm_resource>
        </lrm_resources>
      </lrm>
    </node_state>
  </status>
</cib>

=== ClusterLabs/pacemaker-1.0/crm/pengine/testcases/rsc_dep2.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<!-- must -->
<cib>
  <configuration>
    <crm_config>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
    </crm_config>
    <nodes>
      <node id="node1" uname="node1" type="member"/>
      <node id="node2" uname="node2" type="member"/>
    </nodes>
    <resources>
      <resource id="rsc1" class="heartbeat" type="apache">
        <instance_attributes>
          <attributes>
            <nvpair name="priority" value="1.0"/>
          </attributes>
        </instance_attributes>
      </resource>
      <resource id="rsc2" class="heartbeat" type="apache">
        <instance_attributes>
          <attributes>
            <nvpair name="priority" value="2.0"/>
          </attributes>
        </instance_attributes>
      </resource>
      <resource id="rsc3" class="heartbeat" type="apache">
        <instance_attributes>
          <attributes>
            <nvpair name="priority" value="1.0"/>
          </attributes>
        </instance_attributes>
      </resource>
      <resource id="rsc4" class="heartbeat" type="apache">
        <instance_attributes>
          <attributes>
            <nvpair name="priority" value="2.0"/>
          </attributes>
        </instance_attributes>
      </resource>
    </resources>
    <constraints>
      <rsc_colocation id="same_1_2" from="rsc1" to="rsc2" score="INFINITY"/>
      <rsc_colocation id="same_3_4" from="rsc3" to="rsc4" score="INFINITY"/>
    </constraints>
  </configuration>
  <status>
    <node_state id="node1" uname="node1" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true">
      <lrm>
        <lrm_resources>
          <lrm_resource id="rsc1" last_op="start" rsc_state="started" op_status="0" rc_code="0">
            <lrm_rsc_op id="rsc1" operation="start" rsc_state="started" op_status="0" rc_code="0" call_id="1"/>
          </lrm_resource>
        </lrm_resources>
      </lrm>
    </node_state>
    <node_state id="node2" uname="node2" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true">
      <lrm>
        <lrm_resources>
          <lrm_resource id="rsc4" last_op="start" rsc_state="started" op_status="0" rc_code="0">
            <lrm_rsc_op id="rsc4" operation="start" rsc_state="started" op_status="0" rc_code="0" call_id="1"/>
          </lrm_resource>
        </lrm_resources>
      </lrm>
    </node_state>
  </status>
</cib>

=== ClusterLabs/pacemaker-1.0/pengine/testcases/rsc_location5.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<!-- must not -->
<cib num_updates="1" epoch="1" admin_epoch="0">
  <configuration>
    <crm_config><cluster_property_set id="cib-bootstrap-options"><attributes>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
    </attributes></cluster_property_set></crm_config>
    <nodes>
      <node id="node1" uname="node1" type="member"/>
      <node id="node2" uname="node2" type="member"/>
    </nodes>
    <resources>
      <primitive id="rsc1" class="heartbeat" type="apache"/>
    </resources>
    <constraints>
      <rsc_location id="run_rsc1" rsc="rsc1">
	<rule id="score1" score="1000">
	  <expression id="exp1" attribute="rsc1" operation="#not_colocated"/>
	</rule>
      </rsc_location>
    </constraints>
  </configuration>
  <status>
    <node_state id="node1" ha="active" uname="node1" crmd="online" join="member" expected="member" in_ccm="true">
      <lrm id="any">
        <lrm_resources>
          <lrm_resource id="rsc1" last_op="start" op_status="0" rc_code="0">
            <lrm_rsc_op id="rsc1_start_0" operation="start" interval="0" op_status="0" rc_code="0" call_id="1" crm_feature_set="1.0.6" transition_magic=""/>
	  </lrm_resource>
        </lrm_resources>
      </lrm>
    </node_state>
    <node_state id="node2" ha="active" uname="node2" crmd="online" join="member" expected="member" in_ccm="true"/>
  </status>
</cib>

=== ClusterLabs/pacemaker-1.0/crm/pengine/testcases/simple1.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<cib>
  <configuration>
    <crm_config>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
      <nvpair id="symmetric_cluster" name="symmetric_cluster" value="true"/>
    </crm_config>
    <nodes>
      <node id="node1" uname="node1" type="member"/>
    </nodes>
    <resources>
      <primitive id="rsc1" class="heartbeat" type="apache" priority="1.0"/>
    </resources>
    <constraints>
    </constraints>
  </configuration>
  <status>
    <node_state id="node1" crmd="offline" join="down" expected="down" timestamp="1086187789" in_ccm="true"/>
  </status>
</cib>

=== ClusterLabs/pacemaker-1.0/pengine/testcases/bad3.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<!-- no rsc class -->
<cib num_updates="1" epoch="1" admin_epoch="0">
  <configuration>
    <crm_config><cluster_property_set id="cib-bootstrap-options"><attributes>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
    </attributes></cluster_property_set></crm_config>
    <nodes>
      <node id="node1" uname="node1" type="member"/>
    </nodes>
    <resources>
      <primitive id="rsc1" type="apache"/>
    </resources>
    <constraints>
    </constraints>
  </configuration>
  <status>
    <node_state id="node1" ha="active" uname="node1" crmd="online" join="member" expected="member" in_ccm="true">
      <lrm id="any">
        <lrm_resources>
          <lrm_resource id="rsc1" class="heartbeat" type="apache"/>
        </lrm_resources>
      </lrm>
    </node_state>
  </status>
</cib>

=== ClusterLabs/pacemaker-1.0/crm/pengine/testcases/comments.xml
<?xml version="1.0"?>
<!DOCTYPE cib SYSTEM "crm-1.0.dtd">
<!-- initial -->
<cib>
  <configuration>
    <!-- pre-comment -->
    <crm_config><cluster_property_set id="cib-bootstrap-options"><attributes>
      <nvpair id="no_quorum_policy" name="no_quorum_policy" value="ignore"/>
      <!-- post-comment -->
    </attributes></cluster_property_set></crm_config>
    <nodes>
      <node id="node2" uname="node2" type="member"/>
      <!-- embedded-comment -->
      <node id="node1" uname="node1" type="member"/>
    </nodes>
    <resources>
      <primitive id="rsc1" class="heartbeat" type="apache">
        <instance_attributes>
          <attributes>
            <nvpair name="priority" value="1.0"/>
          </attributes>
        </instance_attributes>
      </primitive>
      <primitive id="rsc2" class="heartbeat" type="apache">
        <instance_attributes>
          <attributes>
            <nvpair name="priority" value="1.0"/>
          </attributes>
        </instance_attributes>
      </primitive>
    </resources>
    <constraints>
      <rsc_location id="run_rsc1" rsc="rsc1">
	<rule id="cannot1" score="-INFINITY" boolean_op="or"><!-- no spaces --><expression id="exp1" attribute="#uname" operation="eq" value="node2"/>
	</rule>
      </rsc_location>
    </constraints>
  </configuration>
  <status>
    <node_state id="node1" uname="node1" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true"/>
    <node_state id="node2" uname="node2" crmd="online" join="member" expected="member" timestamp="1086187789" in_ccm="true"/>
  </status>
</cib>
